---
- name: download tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz
    dest: /opt

- name: extract package
  unarchive:
    src: /opt/apache-tomcat-9.0.31.tar.gz
    dest: /opt
    remote_src: yes

- name: one line added
  lineinfile:
    path: /opt/apache-tomcat-9.0.31/conf/tomcat-users.xml
    insertbefore: '^</tomcat-users>'
    line: '<user username="admin" password="admin" roles="manager-gui,admin-gui,manager-script"/>'
    remote_src: yes

- name: one line replaced
  lineinfile:
    path: /opt/apache-tomcat-9.0.31/conf/server.xml
    regexp: '<Connector port="8080" protocol="HTTP/1.1"'
    line: '<Connector port="8888" protocol="HTTP/1.1"'
    remote_src: yes

- name: one file copies
  template: src=context.xml.j2 dest=/opt/apache-tomcat-{{ tomcat_version }}/webapps/manager/META-INF/context.xml
  notify:
  - start_tomcat
